// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyqhjbkwkdolbmvpzhly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cWhqYmt3a2RvbGJtdnB6aGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE4Njg4MzAsImV4cCI6MjA5NzQ0NDgzMH0.p5Rbg24qg_A_Gg7m_fBdhYsBZYKDmUSBvVtDc3kb-8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});